# Generated by Django 5.2.1 on 2025-05-26 15:06

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.IntegerField()),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'pereval_areas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Coords',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SPRActivityTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'spr_activities_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fam', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('otc', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('connect', models.TextField(blank=True, null=True)),
                ('add_time', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('other_titles', models.CharField(blank=True, max_length=10, null=True)),
                ('winter', models.CharField(blank=True, max_length=10, null=True)),
                ('summer', models.CharField(blank=True, max_length=10, null=True)),
                ('autumn', models.CharField(blank=True, max_length=10, null=True)),
                ('spring', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pend'), ('accepted', 'Acc'), ('rejected', 'Rej')], default='new', max_length=10)),
                ('coord_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adding.coords')),
                ('added_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adding.users')),
            ],
            options={
                'db_table': 'pereval_added',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField()),
                ('img', models.BinaryField()),
                ('title', models.TextField(blank=True, null=True)),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adding.pereval')),
            ],
            options={
                'db_table': 'pereval_images',
                'managed': True,
            },
        ),
    ]
