# Generated by Django 5.2.1 on 2025-05-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
