# Generated by Django 5.2.1 on 2025-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adding', '0002_alter_image_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='other_titles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
