# Generated by Django 5.2.1 on 2025-05-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adding', '0003_alter_pereval_other_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='add_time',
            field=models.DateTimeField(),
        ),
    ]
