# Generated by Django 5.2.1 on 2025-05-22 16:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adding', '0003_alter_users_options_pereval_added_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='other_titles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), default=[], size=None),
        ),
    ]
